name: CI Workflow

on:
  push:
    branches-ignore:
      - release
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Setup
        uses: shopstic/tailscale-nix-builder/setup@9f19de9453fa4aee80e1ad404fb45af87ecbbd15
        timeout-minutes: 1
        with:
          tailscaleAuthKey: ${{ secrets.TAILSCALE_AUTHKEY }}
          nixBuildSshKey: ${{ secrets.NIX_BUILD_SSH_KEY }}

      - name: Build
        run: |-
          nix build -L -v '.#packages.${{ matrix.arch }}-linux' 