name: CI Workflow

on:
  push:
    branches-ignore:
      - release
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build-apps:
    name: Build apps
    needs: build-env
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: nixbuild/nix-quick-install-action@v7
        with:
          nix_version: 2.4pre20210908_3c56f62
          nix_conf: |
            experimental-features = nix-command flakes

      - name: Start buildkitd
        run: |
          ./ci.sh start_buildkitd

      - name: Build
        env:
          GIT_REF: latest
        run: |-
          nix develop -v -c ./ci.sh build_dev