name: Dev

on:
  push:
    branches-ignore:
      - release
      - 'releases/*'
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build-x86_64:
    name: Build x86_64
    runs-on: [self-hosted, nix, amd64-linux]
    outputs:
      digests: ${{ steps.build.outputs.digests }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        id: build
        with:
          imageRepo: public.ecr.aws/shopstic
          arch: x86_64

  build-aarch64:
    name: Build aarch64
    runs-on: [self-hosted, nix, arm64-linux]
    outputs:
      digests: ${{ steps.build.outputs.digests }}
    steps:
      - uses: actions/checkout@v3    
      - uses: ./.github/actions/build
        id: build
        with:
          imageRepo: public.ecr.aws/shopstic
          arch: aarch64

  push:
    name: Push
    runs-on: [self-hosted, nix]
    needs: [build-x86_64, build-aarch64]
    env:
      IMAGE_REPOSITORY: public.ecr.aws/shopstic
    steps:
      - uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: ./.github/actions/login-to-public-ecr
        with:
          imageRepo: ${{ env.IMAGE_REPOSITORY }}

      - name: Push multi-arch manifests
        shell: nix develop -v -c bash {0}
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |-
          manifest-tool push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template "${IMAGE_REPOSITORY}"/iac-version-bumper:dev-ARCH-"${GITHUB_SHA}" \
            --target "${IMAGE_REPOSITORY}"/iac-version-bumper:dev-"${GITHUB_SHA}"

          manifest-tool push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template "${IMAGE_REPOSITORY}"/registry-authenticator:dev-ARCH-"${GITHUB_SHA}" \
            --target "${IMAGE_REPOSITORY}"/registry-authenticator:dev-"${GITHUB_SHA}"

          manifest-tool push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template "${IMAGE_REPOSITORY}"/registry-syncer:dev-ARCH-"${GITHUB_SHA}" \
            --target "${IMAGE_REPOSITORY}"/registry-syncer:dev-"${GITHUB_SHA}"

          manifest-tool push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template "${IMAGE_REPOSITORY}"/fdb-server:dev-ARCH-"${GITHUB_SHA}" \
            --target "${IMAGE_REPOSITORY}"/fdb-server:dev-"${GITHUB_SHA}"
          
          manifest-tool push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template "${IMAGE_REPOSITORY}"/fdb-configurator:dev-ARCH-"${GITHUB_SHA}" \
            --target "${IMAGE_REPOSITORY}"/fdb-configurator:dev-"${GITHUB_SHA}"
          
          manifest-tool push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template "${IMAGE_REPOSITORY}"/k8s-job-autoscaler:dev-ARCH-"${GITHUB_SHA}" \
            --target "${IMAGE_REPOSITORY}"/k8s-job-autoscaler:dev-"${GITHUB_SHA}"
          
          manifest-tool push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template "${IMAGE_REPOSITORY}"/github-actions-registry:dev-ARCH-"${GITHUB_SHA}" \
            --target "${IMAGE_REPOSITORY}"/github-actions-registry:dev-"${GITHUB_SHA}"