name: Dev

on:
  push:
    branches-ignore:
      - release
      - 'releases/*'
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build-x86_64:
    name: Build x86_64
    runs-on: ubuntu-20.04
    outputs:
      digests: ${{ steps.build.outputs.digests }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: ./.github/actions/build
        id: build
        with:
          tailscaleAuthKey: ${{ secrets.TAILSCALE_AUTHKEY }}
          nixBuildSshKey: ${{ secrets.NIX_BUILD_SSH_KEY }}
          dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
          arch: x86_64
      - run: sudo tailscale logout

  build-aarch64:
    name: Build aarch64
    runs-on: ubuntu-20.04
    outputs:
      digests: ${{ steps.build.outputs.digests }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579    
      - uses: ./.github/actions/build
        id: build
        with:
          tailscaleAuthKey: ${{ secrets.TAILSCALE_AUTHKEY }}
          nixBuildSshKey: ${{ secrets.NIX_BUILD_SSH_KEY }}
          dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
          arch: aarch64
      - run: sudo tailscale logout

  push:
    name: Push
    runs-on: ubuntu-20.04
    needs: [build-x86_64, build-aarch64]
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: chmod +r ~/.docker/config.json

      - name: Push multi-arch manifests
        env:
          AMD64_DIGESTS: ${{ needs.build-x86_64.outputs.digests }}
          ARM64_DIGESTS: ${{ needs.build-aarch64.outputs.digests }}
          IMAGE_TAG: dev-${{ github.sha }}
        run: |-
          ./release.sh push_multi_arch_manifest \
            docker.io/shopstic/iac-version-bumper "${IMAGE_TAG}" \
            "$(printenv AMD64_DIGESTS | jq -r '.iac_version_bumper')" \
            "$(printenv ARM64_DIGESTS | jq -r '.iac_version_bumper')"

          ./release.sh push_multi_arch_manifest \
            docker.io/shopstic/fdb-server "${IMAGE_TAG}" \
            "$(printenv AMD64_DIGESTS | jq -r '.fdb_server')" \
            "$(printenv ARM64_DIGESTS | jq -r '.fdb_server')"

          ./release.sh push_multi_arch_manifest \
            docker.io/shopstic/fdb-configurator "${IMAGE_TAG}" \
            "$(printenv AMD64_DIGESTS | jq -r '.fdb_configurator')" \
            "$(printenv ARM64_DIGESTS | jq -r '.fdb_configurator')"