name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache deno
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/.cache
          key: deno-${{ github.sha }}
          restore-keys: |
            deno-
            
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: chmod +r ~/.docker/config.json

      - name: Start buildkitd
        run: |
          ./ci.sh start_buildkitd

      - name: Build
        env:
          SHELL_IMAGE: ghcr.io/shopstic/helmet-mods-ci:${{ hashFiles('shell/*') }}
          DENO_DIR: ${{ github.workspace }}/.cache/deno
          GIT_REF: ${{ github.event.inputs.version }}
        run: |-
          ./ci.sh build_release