name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      sha:
        description: 'Reference commit'
        required: false
        default: ""

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - shell: nix develop '.#release' -v -c bash {0}
        run: |-
          ./release.sh release "${{ github.event.inputs.version }}" "${{ github.event.inputs.sha }}"