name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      sha:
        description: 'Reference commit'
        required: false
        default: ""

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release ${{ github.event.inputs.version }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Setup
        uses: shopstic/tailscale-nix-builder/setup@9f19de9453fa4aee80e1ad404fb45af87ecbbd15
        with:
          tailscaleAuthKey: ${{ secrets.TAILSCALE_AUTHKEY }}
          nixBuildSshKey: ${{ secrets.NIX_BUILD_SSH_KEY }}

      - name: Release
        env:
          REFERENCE_SHA: ${{ github.event.inputs.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IMAGE_TAG=""

          if [[ "${REFERENCE_SHA}" != "" ]]; then
            IMAGE_TAG="dev-${REFERENCE_SHA}"
          fi

          nix develop '.#release' -v -c ./release.sh release "${{ github.event.inputs.version }}" "${IMAGE_TAG}"