name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
      sha:
        description: "Reference commit"
        required: false
        default: ""

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release ${{ github.event.inputs.version }}
    runs-on: [self-hosted, nix, general, arm64-linux, small]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.sha }}

      - name: Release
        env:
          REFERENCE_SHA: ${{ github.event.inputs.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.event.inputs.version }}
        shell: nix develop -v -c bash {0}
        run: |
          DEV_TAG=""
          if [[ "${REFERENCE_SHA}" != "" ]]; then
            DEV_TAG="dev-${REFERENCE_SHA}"
          else
            DEV_TAG=$(./cli.sh generate_image_tag)
          fi

          ./cli.sh release "${DEV_TAG}" "${RELEASE_VERSION}"
