name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: chmod +r ~/.docker/config.json

      - name: Start buildkitd
        run: |
          ./ci.sh start_buildkitd

      - uses: nixbuild/nix-quick-install-action@v7
        with:
          nix_version: 2.4pre20210908_3c56f62
          nix_conf: |
            experimental-features = nix-command flakes

      - name: Build
        env:
          GIT_REF: ${{ github.event.inputs.version }}
        run: |-
          nix develop -v -c ./ci.sh build_release