name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      sha:
        description: 'Reference commit'
        required: false
        default: ""

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release ${{ github.event.inputs.version }}
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Release
        env:
          REFERENCE_SHA: ${{ github.event.inputs.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.event.inputs.version }}
        shell: nix develop -v -c bash {0}
        run: |
          IMAGE_TAG=""
          if [[ "${REFERENCE_SHA}" != "" ]]; then
            IMAGE_TAG="dev-${REFERENCE_SHA}"
          fi

          ./release.sh release public.ecr.aws/g1b1f7a7 "${RELEASE_VERSION}" "${IMAGE_TAG}"